# Generated by Django 5.1.2 on 2024-10-29 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_publication_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Обо компании',
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
            ],
            options={
                'verbose_name': 'Социальные сети и контакт',
                'verbose_name_plural': 'Социальные сети и контакт',
            },
        ),
    ]
