# Generated by Django 5.1.2 on 2024-10-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_aboutcompany_socialmediacontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная публикация'),
        ),
    ]
