# Generated by Django 5.1.2 on 2024-11-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_product_image_alter_publication_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('полукопченые', 'Полукопченые'), ('вареные', 'Вареные'), ('сэндвичи', 'Сэндвичи')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='images/'),
        ),
    ]
